### ISSUE TITLE
Add molecule tests for redpanda role

### ISSUE THREAD

**Issue by tmgstevens** [redpanda-data/deployment-automation#111]
https://molecule.readthedocs.io/en/latest/

Ideally we should add Github actions to help with regression testing as well.

**Comment by gene-redpanda** [comment]
I feel that building out and maintaining molecule unit testing is a burdensome alternative to integration testing -- but am open to hearing an alternative POV! 

I've configured the repo to support local testing against AWS through building the docker container, pasting in your cloud provider creds and then ./.buildkite/scripts/runtask.sh. Total runtime is about 7-10m because it includes standup/teardown. 

It is also possible to cut total runtime substantially below that level by building out infra and then running through the tasks. 

I may set up an explicitly local Dockerfile for testing that includes a cp . /app step to save some time for the user.
